### ISSUE TITLE
impl Radix for RevOrd isn’t helpful since RevOrd isn’t Copy

### ISSUE THREAD

**Issue by andersk** [Noctune/radix-heap#1]
All the `RadixHeapMap` operations require `K: Radix + Ord + Copy`. It seems the intended way to make a min-heap is via the `RevOrd` wrapper, for which a `Radix` implementation is defined. But `RevOrd` can’t actually be used since it doesn’t derive `Copy`.

Perhaps a `Radix` impl for `std::cmp::Reverse` should be added, since `Reverse` derives `Copy` at least in 1.26 beta (rust-lang/rust#47379).

**Comment by Noctune** [comment]
Yeah, now that std has a official reverse order wrapper, it would no doubt be best to use that. I have just pushed a bunch of changes to 0.3 to update it to more modern Rust, including Reverse support.
